### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Gruntfuggly** [chris-kahn/vscode-quick-browser#2]
Hi - I really like this - it's a really nice way to open files outside the workspace.

I've got a couple of requests:

- hide the `. (current directory)` entry. This makes it much easier to move up the tree as the parent folder is pre-selected when the drop down is opened

- add a key to open a folder instead of navigating into it 

Alternatively, keep the `. (current directory)` and use it to open the folder in vscode instead. If you do this, could you swap the `.` and `..` entries around so that it's still easy to navigate upwards?

**Comment by chris-kahn** [comment]
The order is like that because I wanted to replicate the behaviour of Emacs and `ls -la` which sorts `.` and `..`, but you're right it could be more useful to have the parent directory at the top.

I'm planning to make `.` open the selected directory in vscode, that's sort of what Emacs does, it opens it in dired.

**Comment by Gruntfuggly** [comment]
It occured to me after I raised it that it was probably intended to be in that order. 8-)

I had a quick hack around to make it work, if you want it:

```
    if( selectedLabel === "." ) {
        vscode.commands.executeCommand( 'vscode.openFolder', new vscode.Uri( { scheme: 'file', path: qp.placeholder } ), false );
    }
    else {
        updateQuickPick( qp, newPath );
    }
```

which opens the folder in the same window...

**Comment by chris-kahn** [comment]
This command will open the folder, but it basically reloads the window with only the new folder open. If you had a workspace or other folders open those are closed... as opposed to adding the folder to the current workspace. I'm not sure what's the right behaviour. Could make it configurable!

**Comment by chris-kahn** [comment]
For now I've reversed the order of `.` and `..`, I agree it's a lot more convenient that way.

**Comment by Gruntfuggly** [comment]
I think the boolean flag after the openFolder command tells it to open in a new window or not. I think that's sufficient for when you are not using workspace folders - which is what I do at the moment, but I assume there are better commands for manipulating the folders if you are?

**Comment by chris-kahn** [comment]
I can do a check to see if there's an open workspace, so we can call openFolder by default and then use updateWorkspaceFolders if there's an open workspace.

**Comment by Gruntfuggly** [comment]
I tried updateWorkspaceFolders in a non-workspace window and a workspace window and couldn't get it to work in either (I didn't try too hard though). It just returns a boolean if it fails, rather than an error. Hopefully you'll have more luck. 8-)

**Comment by Gruntfuggly** [comment]
BTW - did you delete and republish - I thought I left you a rating and a review :confused: ?

**Comment by chris-kahn** [comment]
I did.... it didn't seem to pick up my change to the repository URL otherwise 🙄

**Comment by Gruntfuggly** [comment]
Ah OK - I'm not going nuts then! :grinning:

**Comment by chris-kahn** [comment]
I've (finally) updated the extension to incorporate your changes :D hope it's useful that way! Please feel free to suggest more improvements.

**Comment by Gruntfuggly** [comment]
Looks good - thanks!
