### ISSUE TITLE
Opening from an new file fails

### ISSUE THREAD

**Issue by Gruntfuggly** [chris-kahn/vscode-quick-browser#3]
If I open the browser from a new 'Untitled' file, I get the error
```
ENOENT: no such file or directory, scandir '~'
```
(I'm running under Ubuntu)

I see that it warns if you try to open the browser without an open editor. Would it be possible to default to the users home folder in this case?

**Comment by chris-kahn** [comment]
Good catch. If a workspace is open it defaults to the workspace folder, but if there are no workspaces it fails. I'll make it default to the user's home folder.

**Comment by chris-kahn** [comment]
This should be working in 1.0.3, let me know if it's still broken ;)
