### ISSUE TITLE
Keys are overwritten at Win environment.

### ISSUE THREAD

**Issue by ezh** [chris-kahn/vscode-quick-browser#5]
Alt+LeftArrow is used for Go Back and so on.
It will be better to add when clause to fix this issue.
PR will be available shortly.

Thank you for the splendid extension! 👍 💯 

P.S. Would you mind to add short animated Git to Readme? It will be cool for all other vscode users.

**Comment by chris-kahn** [comment]
Good idea about adding a gif 👍
